# Alob Project
# 2016 - 2018
# Author(s): R.Walker
#
name: alob_c_env_py3k
dependencies:
- python=3.6
- bokeh=0.12.10
- ipython
- numpy=1.13
- pandas=0.22
- scipy=1.0
- xlrd
- xlsxwriter
- sphinx
- scikit-learn=0.19
- scikit-image=0.13
- psutil
- pip:
  - django=1.11
  - django-bootstrap3
  - django-extensions
  - django-filter
  - django-settings-export
  - joblib
  - mysqlclient