# Alob Project
# 2016 - 2018
# Author(s): R.Walker
#
name: alob_c_env_py3k
dependencies:
- python=3.7
- conda-build
- bokeh
- ipython
- numpy
- pandas
- scipy
- xlrd
- xlsxwriter
- sphinx
- scikit-learn
- scikit-image
- psutil
- pip
- pip:
  - django
  - django-bootstrap3
  - django-extensions
  - django-filter
  - django-settings-export
  - joblib
  - mysqlclient