# Alob Project
# 2016 - 2018
# Author(s): R.Walker
#
name: alob_c_env_py3k
dependencies:
- python=3.6
- django=1.11
- bokeh=0.12.10
- ipython
- numpy
- pandas
- scipy
- xlrd
- xlsxwriter
- sphinx
- scikit-learn
- psutil
- pip:
  - django-bootstrap3
  - django-extensions
  - django-filter
  - django-settings-export
  - joblib
  - mysqlclient

