# Alob Project
# 2016 - 2018
# Author(s): R.Walker
#
name: alob_c_env_py3k
dependencies:
- python=3.7
- conda-build
- bokeh=1.4
- ipython
- numpy=1.18
- pandas=1.0
- scipy=1.4
- sphinx
- scikit-learn=0.22
- scikit-image=0.16
- psutil
- pip
- pip:
  - django==3.0
  - django-bootstrap3
  - django-extensions
  - django-filter
  - django-settings-export
  - xlrd
  - xlsxwriter
  - joblib
  - mysqlclient==1.4